### ISSUE TITLE
Cnn_keras converting to float 32

### ISSUE THREAD

**Issue by alinakhay** [gregwchase/nih-chest-xray#1]
Hi! First of all, thank you very much for this great contribution and sharing of your deep learning model with us. I would like to ask the question with regards to converting X_train and X_test to 'float32' in cnn_keras.py. The point is, I get the 'Memory error' when running your code with images scaled to 512x512, how do you go about solving this one?

Thank you very much once again!

**Comment by gregwchase** [comment]
@alinakhay Thank you - great to hear people are getting something out of it!

Regarding your question: scaling the images may make you run into OOM errors (not just with my model, but with others).

Something Keras has implemented is the multi_gpu_model parameter; you can place the line directly above `model.compile`. Assuming you're using more than one GPU, this might solve the OOM issues. I haven't implemented it yet in EyeNet, but it'll be here soon!

`model = multi_gpu_model(model, gpus=nb_gpus)`
https://keras.io/utils/#multi_gpu_model

**Comment by alinakhay** [comment]
Thank you for your response @gregwchase , yes I have done so already, using 256 - it worked and then some other issue came up, which I won't bother you with :)
